version: '3.8'

services:
  # Relational Database (Cold Layer)
  postgres-db:
    image: postgres:16-alpine
    container_name: trading_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: SamTrades@2908
      POSTGRES_DB: trading_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # In-Memory Cache (Hot Layer)
  redis-cache:
    image: redis:7-alpine
    container_name: trading_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local